---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfdiegodocker/deploy-cf-deployment

inputs:
- name: diego-ci
- name: deployments-diego

run:
  path: diego-ci/concourse/bosh_delete_deployments

PARAMS:
  BOSH_ENVIRONMENT: ~
  BOSH_CLIENT: ~
  BOSH_CLIENT_SECRET: ~
  DEPLOYMENT_DIR: ~
  DEPLOYMENTS: ~
