---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfdiegodocker/deploy-cf-deployment

inputs:
  - name: deployments-diego
  - name: diego-ci
  - name: cf-mysql-deployment

params:
  DEPLOYMENTS_DIR: ~
  ENVIRONMENT_NAME: ~

run:
  path: diego-ci/concourse/deploy_cf_mysql_deployment
