---
platform: linux

image: docker:///cloudfoundry/diego-pipeline

inputs:
  - name: deployments-diego
  - name: diego-release
  - name: cf-release
  - name: diego-ci

outputs:
  - name: generated-manifest

params:
  DEPLOYMENTS_DIR: ~
  ENVIRONMENT_NAME: ~
  INFRASTRUCTURE: ~

run:
  path: diego-ci/concourse/generate_windows_cell_deployment_manifest
