---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/diego-pipeline

inputs:
  - name: deployments-diego
  - name: diego-release
  - name: cf-release
  - name: diego-ci

outputs:
  - name: generated-manifest

params:
  DEPLOYMENTS_DIR: ~
  ENVIRONMENT_NAME: ~
  INFRASTRUCTURE: ~
  USE_LOCAL_ROUTE_EMITTERS: false
  USE_LOCKET_SQL_LOCK: false

run:
  path: diego-ci/concourse/generate_windows_cell_deployment_manifest
