---
platform: linux

image: docker:///cloudfoundry/diego-pipeline

inputs:
  - name: deployments-diego
  - name: diego-release
  - name: diego-ci
  - name: cf-release

outputs:
  - name: generated-manifest

params:
  DEPLOYMENTS_DIR: ~
  ENVIRONMENT_NAME: ~
  INFRASTRUCTURE: ~
  USE_LOCAL_ROUTE_EMITTERS: false
  USE_LOCKET_SQL_LOCK_FOR_BBS: false
  USE_GROOTFS: false
  USE_CFLINUX: false
  DEPLOY_POSTGRES: false

run:
  path: diego-ci/concourse/generate_deployment_manifests
