---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfdiegodocker/deploy-cf-deployment

inputs:
- name: diego-ci
- name: cf-deployment-test-branch

outputs:
- name: merged-cf-deployment

run:
  path: diego-ci/concourse/merge_cf_deployment_develop
