---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfdiegodocker/deploy-cf-deployment

inputs:
- name: bosh-stemcell
- name: diego-ci
- name: cf-deployment
- name: diego-release

outputs:
- name: cf-deployment

run:
  path: diego-ci/concourse/merge_cf_deployment
