---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfdiegodocker/deploy-cf-deployment

inputs:
- name: cf-deployment
- name: cf-deployment-diego

outputs:
- name: merged-cf-deployment

run:
  path: diego-ci/concourse/merge_cf_deployment
