---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfdiegodocker/deploy-cf-deployment

inputs:
- name: diego-ci
- name: cf-deployment-develop

outputs:
- name: merged-cf-deployment

params:
  PRIVATE_KEY:

run:
  path: diego-ci/concourse/merge_into_cf_deployment_diego
